import { Game } from '@/lib/games/catalog';

// Game metadata
export const MUTIRAO_GAME: Game = {
  id: 'mutirao-de-saneamento',
  slug: 'mutirao-de-saneamento',
  title: 'Mutirão de Saneamento',
  shortDescription: 'Mobilize a comunidade para levar saneamento básico a um bairro.',
  description: 'Na Vila Esperança, na Baixada Fluminense, 500 famílias vivem sem esgoto tratado e com água encanada irregular. A prefeitura promete desde 2018. Neste jogo, você atua como organizador comunitário, mobilizando vizinhos, alocando recursos escassos e construindo soluções coletivas. Experimente o poder — e o peso — da organização popular em busca de direitos básicos.',
  genre: 'simulation',
  theme: 'city',
  status: 'beta',
  runtimeState: 'real',
  estimatedMinutes: 5,
  duration: '5 min',
  participants: 1,
  difficulty: 'medium',
  tags: ['simulação', 'saneamento', 'baixada', 'organização'],
  cta: 'Mobilizar',
  color: '#228B22',
  kind: 'simulation',
  line: 'organizacao-popular',
  pace: 'session',
  territoryScope: 'baixada',
  territories: ['baixada'],
  politicalThemes: ['organizacao-popular', 'cuidado', 'moradia', 'servicos-publicos'],
  series: 'territorios-em-luta',
  politicalAxis: 'poder-popular',
  collectiveSolutionType: 'ajuda-mutua',
  commonVsMarket: 'comum',
  campaignFrame: 'comunidade-em-luta',
  season: 's1-verao-26',
  campaignRole: 'Experimentar o peso da escassez e a força do coletivo.',
  funRole: 'aprofundamento',
  deviceSupport: ['mobile', 'desktop'],
  priorityScore: 70,
  publicVisibility: 'public_ready_beta',
  icon: '🚰',
  cover: '/images/games/mutirao-saneamento/cover.jpg',
};
